

server:
  port: 8080



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_app_apis
    username: root
    password: jaiganeshji
    driver-class-name: com.mysql.cj.jdbc.Driver


 # security:
 #   user:
 #     name: hims
 #     password: hims
 #     roles:
 #       - ADMIN




# corr. to  'spring.security.user.name' and 'spring.security.user.password' and 'spring.security.user.roles'



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: org.hibernate.dialect.MySQL8Dialect



  servlet:
    multipart:
      max-file-size: 10MB

      max-request-size: 10MB



project:
  image: images/




logging:
  level:
    org:
      springframework:
        security: DEBUG




# https://www.baeldung.com/spring-security-enable-logging

# https://howtodoinjava.com/spring-boot/configure-logging-application-yml/






springdoc:
  api-docs:
    path: /api-docs

# Default is  http://localhost:8080/v3/api-docs


  swagger-ui:
    path: /swagger-ui-custom.html

# Default is  http://localhost:8080/swagger-ui/index.html




#springdoc.api-docs.enabled=false
#springdoc.swagger-ui.enabled=false




# springdoc.swagger-ui.path=/bezkoder-documentation
# springdoc.api-docs.path=/bezkoder-api-docs
  
# springdoc.packages-to-scan=com.bezkoder.spring.swagger.controller
# springdoc.swagger-ui.tryItOutEnabled=true
# springdoc.swagger-ui.operationsSorter=method
# springdoc.swagger-ui.tagsSorter=alpha
# springdoc.swagger-ui.filter=true










